OpenCurves: PlotInstance Class Reference
PlotInstance Class Reference
API Reference Documentation » Plot Support
Holds data for a single curve.
#include <plotinstance.h>
Public Types
enum Flag {
DataComplete = (1 << 0), RingBuffer = (1 << 1), ExplicitColour = (1 << 2), FilterNaN = (1 << 3),
FilterInf = (1 << 4), ExplicitTime = (1 << 5)
}
Status, control and display flags.
enum Defaults { DefaultSymbolSize = 5 }
Some default values for plots.
Public Member Functions
PlotInstance (const PlotSource::Ptr &source)
Create a plot instance from the given source.
PlotInstance (const PlotInstance &other)
Copy constructor.
~PlotInstance ()
Destructor.
PlotSource & source ()
Access the plot source.
const PlotSource & source () const
Access the plot source.
void setDefaultProperties ()
Restore the default style, colour, etc properties.
QString name () const
Get the plot name.
void setName (QString name)
Set the plot name.
int style () const
Get the draw style: matches QwtPlotCurve::CurveStyle.
void setStyle (unsigned style)
Set the draw style: matches QwtPlotCurve::CurveStyle.
unsigned width () const
Get the draw width.
void setWidth (unsigned width)
Set the pen draw width: limited to 255.
int symbol () const
Get the draw symbol: matches QwtSymbol::Style.
void setSymbol (int symbol)
Set the draw symbol: matches QwtSymbol::Style.
unsigned symbolSize () const
Get the symbol size.
void setSymbolSize (unsigned size)
Set the symbol size: limited to 255.
const std::vector< QPointF > & data () const
Direct access to the data buffer.
const QRgb & colour () const
Get the display colour for the plot.
void setColour (const QRgb &colour, bool markExplicit=true)
Set the display colour, making it explicit unless requested otherwise.
const PlotExpression * expression () const
Get the expression which generated this plot (Expression source() only).
void setExpression (const PlotExpression *expression)
Sets the expression which generated this plot.
size_t ringHead () const
The read head of the ring buffer.
std::uint16_t flags () const
Get the status, control and display Flag values.
bool testFlags (std::uint16_t flags)
Sets that all flags are set in the flags() member.
bool dataComplete () const
Is data loading complete?
void setComplete ()
Marks data complete.
bool isRingBuffer () const
Is this a ring buffer?
void makeRingBuffer (size_t bufferSize)
Converts the plot data to a ring buffer of the given size.
bool explicitColour () const
Using an explicit colour?
bool filterNaN () const
Filter NaN values on display?
void setFilterNaN (bool filter)
Set or clear NaN filtering.
bool filterInf () const
Filter infinite values on display?
void setFilterInf (bool filter)
Set or clear infinite value filtering.
bool explicitTime () const
Has the curve been generated with explicit time values?
void setExplicitTime (bool explct)
Set the state of the ExplicitTime Flag.
QPointF sample (size_t index) const
Samples the point at the given index.
void addPoint (const QPointF &p)
Add a point to the back buffer (thread-safe).
void addPoints (const QPointF *points, size_t pointCount)
Add multiple points to the back buffer.
bool migrateBuffer ()
Migrate from the back buffer to data(). Main thread only.
PlotInstance & operator= (const PlotInstance &other)
Assignment operator.
Detailed Description
Holds data for a single curve.
Supports thread-safe, double buffered loading. The data source thread should call addPoint() or addPoints() to add data. Meanwhile the main thread should periodically call migrateBuffer() to move data into the front buffer. Note that only the back buffer is thread-safe. The sample() function should only be called either by the main thread (the same thread doing the migration) or once all data are loaded.
While data can be sampled directly via sample(), a PlotInstanceSampler should be used to resolve time values and time scaling.
Ring Buffer Mode
The structure may be operating in ring buffer mode, in which case the data array is fixed size and added to as a ring buffer. The ringHead marks the start of the ring buffer. The ring buffer is full once the data size equals its capacity.
The PlotInstanceSampler handles sampling in ring buffer mode.
Member Enumeration Documentation
enum PlotInstance::Defaults
Some default values for plots.
Enumerator
DefaultSymbolSize
Default size for displaying plot symbols.
enum PlotInstance::Flag
Status, control and display flags.
Enumerator
DataComplete
Set when all data have been loaded and the curve is complete.
No further calls to migrateBuffer() required.
RingBuffer
Set if the data member acts as a ring buffer. Affects sample(), addPoint(), addPoints().
ExplicitColour
Set if the graph has been assigned an explicit colour.
No colour shift will be performed in plotting the curve.
FilterNaN
Set to filter NaN values, replacing them with zero.
FilterInf
Set to filter infinite values, replacing them zero.
ExplicitTime
Has the curve been generated with explicit time samples? Some generated curves have explicit times and are not subject to time scaling, time shift or time columns.
Such curves may need to be renenerated if timing information is changed.
Constructor & Destructor Documentation
PlotInstance::PlotInstance (const PlotSource::Ptr & source)
Create a plot instance from the given source.
Parameters
source The plot source.
Member Function Documentation
void PlotInstance::addPoint (const QPointF & p)
Add a point to the back buffer (thread-safe).
Parameters
p The point to add.
void PlotInstance::addPoints (const QPointF * points, size_t pointCount)
Add multiple points to the back buffer.
Parameters
points The points array to add.
pointCount The element count of points.
const QRgb& PlotInstance::colour () const inline
Get the display colour for the plot.
May be colour shifted when explicitColour() is false.
Returns
The preferred display colour.
Referenced by setColour().
const std::vector<QPointF>& PlotInstance::data () const inline
Direct access to the data buffer.
Use sample() for controlled access including ring buffer handling.
Returns
The internal data buffer (visible buffer).
bool PlotInstance::dataComplete () const inline
Is data loading complete?
Returns
True if all data are present. No further calls to migrateBuffer() required.
References DataComplete.
bool PlotInstance::explicitColour () const inline
Using an explicit colour?
Returns
True if using an explicit colour.
References ExplicitColour.
bool PlotInstance::explicitTime () const inline
Has the curve been generated with explicit time values?
Returns
True if generated with explicit time values.
References ExplicitTime.
const PlotExpression* PlotInstance::expression () const inline
Get the expression which generated this plot (Expression source() only).
Note: this is a shared pointer.
Returns
The generating expression.
Referenced by setExpression().
bool PlotInstance::filterInf () const inline
Filter infinite values on display?
Returns
True if filtering infinite values.
References FilterInf.
bool PlotInstance::filterNaN () const inline
Filter NaN values on display?
Returns
True if filtering NaN.
References FilterNaN.
std::uint16_t PlotInstance::flags () const inline
Get the status, control and display Flag values.
Returns
The set Flag values.
Referenced by testFlags().
bool PlotInstance::isRingBuffer () const inline
Is this a ring buffer?
Returns
True if using a ring buffer.
References RingBuffer.
void PlotInstance::makeRingBuffer (size_t bufferSize)
Converts the plot data to a ring buffer of the given size.
This may (safely) resize the existing ring buffer if already a ring buffer.
Parameters
bufferSize The size of the ring buffer.
QString PlotInstance::name () const inline
Get the plot name.
Returns
The plot name.
Referenced by setName().
PlotInstance& PlotInstance::operator= (const PlotInstance & other)
Assignment operator.
Copies all members excluding the data back buffer.
Parameters
other The object to copy.
size_t PlotInstance::ringHead () const inline
The read head of the ring buffer.
Always zero if not isRingBuffer().
Returns
The read head index.
QPointF PlotInstance::sample (size_t index) const
Samples the point at the given index.
This caters for ring buffer sampling.
For a non-ring buffer, the index must be in range. For a ring buffer, the index is wrapped into the valid range, except when the buffer is empty.
Parameters
index The sampling index.
void PlotInstance::setColour (const QRgb & colour, bool markExplicit = true) inline
Set the display colour, making it explicit unless requested otherwise.
Parameters
colour The new colour.
markExplicit True to make explictColour() true, preventing colour shift (default).
References colour(), and ExplicitColour.
void PlotInstance::setExplicitTime (bool explct) inline
Set the state of the ExplicitTime Flag.
Parameters
explct True to set ExplicitTime, false to clear.
References ExplicitTime.
void PlotInstance::setExpression (const PlotExpression * expression) inline
Sets the expression which generated this plot.
Should only be called for Expression source().
Parameters
expression The generating expression.
References expression().
void PlotInstance::setFilterInf (bool filter) inline
Set or clear infinite value filtering.
Parameters
filter True to turn on filtering, false to turn off.
References FilterInf.
void PlotInstance::setFilterNaN (bool filter) inline
Set or clear NaN filtering.
Parameters
filter True to turn on filtering, false to turn off.
References FilterNaN.
void PlotInstance::setName (QString name) inline
Set the plot name.
Parameters
name The new plot name.
References name().
void PlotInstance::setStyle (unsigned style) inline
Set the draw style: matches QwtPlotCurve::CurveStyle.
Parameters
style The new style.
void PlotInstance::setSymbol (int symbol) inline
Set the draw symbol: matches QwtSymbol::Style.
Parameters
symbol The new symbol.
void PlotInstance::setSymbolSize (unsigned size) inline
Set the symbol size: limited to 255.
Parameters
size The new symbol size.
void PlotInstance::setWidth (unsigned width) inline
Set the pen draw width: limited to 255.
Parameters
width The new width.
PlotSource & PlotInstance::source () inline
Access the plot source.
Returns
The PlotSource owning this plot.
const PlotSource & PlotInstance::source () const inline
Access the plot source.
Returns
The PlotSource owning this plot.
int PlotInstance::style () const inline
Get the draw style: matches QwtPlotCurve::CurveStyle.
Returns
The style type.
int PlotInstance::symbol () const inline
Get the draw symbol: matches QwtSymbol::Style.
Returns
The symbol type.
unsigned PlotInstance::symbolSize () const inline
Get the symbol size.
Returns
The symbol size.
bool PlotInstance::testFlags (std::uint16_t flags) inline
Sets that all flags are set in the flags() member.
Returns
True if all bits an values are set internally.
References flags().
unsigned PlotInstance::width () const inline
Get the draw width.
Returns
The line width.
The documentation for this class was generated from the following file:
plotinstance.h