OpenCurves: PlotUnaryOperator Class Reference
PlotUnaryOperator Class Reference
API Reference Documentation » Plot Expressions
An extension of PlotExpression defining a unary operation.
#include <plotunaryoperator.h>
Public Member Functions
PlotUnaryOperator (PlotExpression *operand)
Create a binary operator on the given left and right expressions.
~PlotUnaryOperator ()
Destructor, destroying the child.
void setOperand (PlotExpression *operand)
Set the operand expression.
const PlotExpression * operand () const
Get the operand expression.
virtual BindResult bind (const QList< PlotInstance * > &curves, PlotBindingTracker &bindTracker, PlotExpressionBindDomain &domain, bool repeatLastBinding=false)
Binds the operand expression.
virtual void unbind ()
Unbind the operand.
bool explicitTime () const override
Is the generated expression sensitive to changes in the time domain?
Public Member Functions inherited from PlotExpression
PlotExpression ()
Empty constructor.
virtual ~PlotExpression ()
Empty, virtual destructor.
virtual double sample (double sampleTime) const =0
Called to generate a sample at sampleTime.
virtual PlotExpression * clone () const =0
Performs a deep clone of the PlotExpression.
QString toString () const
Converts the PlotExpression into a parseable string form.
Detailed Description
An extension of PlotExpression defining a unary operation.
This tracks the child and manages binding, but derivations are required to implement the sample() function.
Constructor & Destructor Documentation
PlotUnaryOperator::PlotUnaryOperator (PlotExpression * operand) inline
Create a binary operator on the given left and right expressions.
Parameters
operand The child expression.
Member Function Documentation
bool PlotUnaryOperator::explicitTime () const override virtual
Is the generated expression sensitive to changes in the time domain?
Returns
True if the child returns true.
Reimplemented from PlotExpression.
const PlotExpression* PlotUnaryOperator::operand () const inline
Get the operand expression.
Returns
The operand.
Referenced by PlotUnaryOperatorT< std::negate< double > >::clone(), PlotUnaryOperatorT< std::negate< double > >::sample(), and setOperand().
void PlotUnaryOperator::setOperand (PlotExpression * operand) inline
Set the operand expression.
Does not release the existing expression.
Parameters
operand The new operand.
References operand().
The documentation for this class was generated from the following file:
plotunaryoperator.h