OpenCurves: PlotZoomer Class Reference
PlotZoomer Class Reference
API Reference Documentation » User Interface
Custom zoom handler for Plot objects.
#include <plotzoomer.h>
Public Types
enum ZoomMode { ZoomBoth, ZoomX, ZoomY, ZoomModeCount }
Zooming mode.
typedef QwtPlotZoomer Super
Parent class.
Public Slots
void setZoomMode (ZoomMode mode)
Set the active ZoomMode.
void setZoomModeBoth ()
Set the zoom mode to ZoomBoth.
void setZoomModeX ()
Set the zoom mode to ZoomX.
void setZoomModeY ()
Set the zoom mode to ZoomY.
void zoomSync (const QRectF &rect)
Event for zoom synchronisation.
Signals
void zoomModeChanged (int mode)
Notifies changes in zoomMode().
void zoomModeBoth (bool isset)
Signal for changes to/from ZoomBoth.
void zoomModeX (bool isset)
Signal for changes to/from ZoomX.
void zoomModeY (bool isset)
Signal for changes to/from ZoomY.
Public Member Functions
PlotZoomer (QwtPlotCanvas *plot, bool doReplot=true)
Constructor, operating on the given plot.
~PlotZoomer ()
Destructor.
ZoomMode zoomMode () const
Access the current ZoomMode.
QAction * zoomBothAction () const
Fetch the action used to select the ZoomBoth mode.
QAction * zoomXAction () const
Fetch the action used to select the ZoomX mode.
QAction * zoomYAction () const
Fetch the action used to select the ZoomY mode.
void loadSettings (QSettings &settings)
Load zoom settings stored by saveSettings().
void saveSettings (QSettings &settings)
Save zoom settings to settings.
void fitIfAutoScaling ()
Set current zoom to fit if auto scaling is enabled.
void zoomToFit (bool replot=true)
Zoom to fit even if auto-scaling is off.
void zoom (const QRectF &rect) override
Override to prevent catastrophic event propagation on synchronised zoom response.
void zoom (int up) override
Override to set auto scaling when reaching zoom level zero.
Static Public Attributes
static const unsigned int AxisY = 0
YAxis reference within QwtPlot.
static const unsigned int AxisX = 2
XAxis reference within QwtPlot.
Protected Slots
void zoomActionToggled (bool checked)
Bound to zoom actions simply to ensure one is kept active.
Protected Member Functions
void widgetMousePressEvent (QMouseEvent *event) override
End panning or reset the zoom level on right mouse button.
void widgetMouseReleaseEvent (QMouseEvent *event) override
Ignore middle click - handled by panner - resolve right click zoom restore or context menu.
void widgetWheelEvent (QWheelEvent *event) override
Cycle zoom levels on wheel.
bool end (bool ok=true) override
Overload to handle ZoomMode.
Detailed Description
Custom zoom handler for Plot objects.
Extends zoom functionality to handle mouse wheel cycling through zoom levels, middle mouse panning and right mouse reset.
Member Enumeration Documentation
enum PlotZoomer::ZoomMode
Zooming mode.
Enumerator
ZoomBoth
Zoom both axes.
ZoomX
Zoom only X axis.
ZoomY
Zoom only Y axis.
Constructor & Destructor Documentation
PlotZoomer::PlotZoomer (QwtPlotCanvas * plot, bool doReplot = true) explicit
Constructor, operating on the given plot.
Parameters
plot The plot to operate on.
doReplot Call QwtPlot::replot() for the attached plot before initializing the zoomer with its scales. This might be necessary, when the plot is in a state with pending scale changes.
Member Function Documentation
void PlotZoomer::loadSettings (QSettings & settings)
Load zoom settings stored by saveSettings().
Note: zoomToFit() is called if the stack size is 1 or empty. This enforces auto scaling when there is no active stack.
Parameters
settings The object to load from.
See also
saveSettings()
void PlotZoomer::saveSettings (QSettings & settings)
Save zoom settings to settings.
Settings are stored in a group labelled "zoom". The following settings are stored:
Key Description
mode The zoomMode()
index The current zoomRectIndex() in the zoomStack()
stack The zoomStack() as a array of rectangles (see below)
Each zoom rectangle is written as:
Key Description
x The X position
y The Y position
w The rectangle width
h The rectangle height
Parameters
settings The object to save to.
void PlotZoomer::setZoomMode (ZoomMode mode) slot
Set the active ZoomMode.
Raises the zoomModeChanged() signal if the mode differs from the current mode.
Parameters
mode The mode to set.
Referenced by setZoomModeBoth(), setZoomModeX(), and setZoomModeY().
void PlotZoomer::widgetMousePressEvent (QMouseEvent * event) override protected
End panning or reset the zoom level on right mouse button.
Parameters
event The mouse event.
void PlotZoomer::widgetMouseReleaseEvent (QMouseEvent * event) override protected
Ignore middle click - handled by panner - resolve right click zoom restore or context menu.
Parameters
event The mouse event.
void PlotZoomer::widgetWheelEvent (QWheelEvent * event) override protected
Cycle zoom levels on wheel.
Parameters
event The mouse event.
void PlotZoomer::zoom (const QRectF & rect) override
Override to prevent catastrophic event propagation on synchronised zoom response.
Parameters
rect The zoom rectangle.
void PlotZoomer::zoom (int up) override
Override to set auto scaling when reaching zoom level zero.
Parameters
up The number of zoom steps to make.
QAction* PlotZoomer::zoomBothAction () const inline
Fetch the action used to select the ZoomBoth mode.
Returns
The ZoomBoth action.
References ZoomBoth.
ZoomMode PlotZoomer::zoomMode () const inline
Access the current ZoomMode.
Returns
The current ZoomMode.
void PlotZoomer::zoomModeBoth (bool isset) signal
Signal for changes to/from ZoomBoth.
Parameters
isset True if ZoomBoth is the new zoom mode.
void PlotZoomer::zoomModeX (bool isset) signal
Signal for changes to/from ZoomX.
Parameters
isset True if ZoomX is the new zoom mode.
void PlotZoomer::zoomModeY (bool isset) signal
Signal for changes to/from ZoomY.
Parameters
isset True if ZoomY is the new zoom mode.
void PlotZoomer::zoomSync (const QRectF & rect) slot
Event for zoom synchronisation.
The whole zoom stack is synchronised if the sender is a QwtPlotZoomer.
void PlotZoomer::zoomToFit (bool replot = true)
Zoom to fit even if auto-scaling is off.
Parameters
replot Force replot after the zoom?
QAction* PlotZoomer::zoomXAction () const inline
Fetch the action used to select the ZoomX mode.
Returns
The ZoomX action.
References ZoomX.
QAction* PlotZoomer::zoomYAction () const inline
Fetch the action used to select the ZoomY mode.
Returns
The ZoomY action.
References ZoomY.
The documentation for this class was generated from the following file:
plotzoomer.h