OpenCurves: PlotBinaryOperator Class Reference
PlotBinaryOperator Class Reference
API Reference Documentation » Plot Expressions
An extension of PlotExpression defining a binary operation.
#include <plotbinaryoperator.h>
Public Member Functions
PlotBinaryOperator (PlotExpression *left, PlotExpression *right)
Create a binary operator on the given left and right expressions.
~PlotBinaryOperator ()
Destructor, destroying left and right.
void setLeft (PlotExpression *left)
Set the left branch.
const PlotExpression * left () const
Get the left branch.
void setRight (PlotExpression *right)
Set the right branch.
const PlotExpression * right () const
Get the right branch.
virtual BindResult bind (const QList< PlotInstance * > &curves, PlotBindingTracker &bindTracker, PlotExpressionBindDomain &domain, bool repeatLastBinding=false)
Binds the left and right branch expressions.
virtual void unbind ()
Unbind left and right branches.
bool explicitTime () const override
Is the generated expression sensitive to changes in the time domain?
Public Member Functions inherited from PlotExpression
PlotExpression ()
Empty constructor.
virtual ~PlotExpression ()
Empty, virtual destructor.
virtual double sample (double sampleTime) const =0
Called to generate a sample at sampleTime.
virtual PlotExpression * clone () const =0
Performs a deep clone of the PlotExpression.
QString toString () const
Converts the PlotExpression into a parseable string form.
Detailed Description
An extension of PlotExpression defining a binary operation.
This is essentially a binary in the expression tree.
This tracks the branches and manages binding, but derivations are required to implement the sample() function.
Constructor & Destructor Documentation
PlotBinaryOperator::PlotBinaryOperator (PlotExpression * left, PlotExpression * right) inline
Create a binary operator on the given left and right expressions.
Parameters
left The left expression.
right The right expression.
Member Function Documentation
virtual BindResult PlotBinaryOperator::bind (const QList< PlotInstance * > & curves, PlotBindingTracker & bindTracker, PlotExpressionBindDomain & domain, bool repeatLastBinding = false) virtual
Binds the left and right branch expressions.
Handles exhaustive binding.
Implements PlotExpression.
bool PlotBinaryOperator::explicitTime () const override virtual
Is the generated expression sensitive to changes in the time domain?
Returns
True if any child returns true.
Reimplemented from PlotExpression.
const PlotExpression* PlotBinaryOperator::left () const inline
Get the left branch.
Returns
The left branch.
Referenced by PlotBinaryOperatorT< std::minus< double > >::clone(), PlotBinaryOperatorT< std::minus< double > >::sample(), and setLeft().
const PlotExpression* PlotBinaryOperator::right () const inline
Get the right branch.
Returns
The right branch.
Referenced by PlotBinaryOperatorT< std::minus< double > >::clone(), PlotBinaryOperatorT< std::minus< double > >::sample(), and setRight().
void PlotBinaryOperator::setLeft (PlotExpression * left) inline
Set the left branch.
Does not release the existing branch.
Parameters
left The new branch.
References left().
void PlotBinaryOperator::setRight (PlotExpression * right) inline
Set the right branch.
Does not release the existing branch.
Parameters
right The new branch.
References right().
The documentation for this class was generated from the following file:
plotbinaryoperator.h